use std::collections::HashMap;

use once_cell::sync::Lazy;

pub(crate) static KEYCODE_ALIAS: Lazy<HashMap<&str, &str>> = Lazy::new(|| {
    let mut m = HashMap::new();

    macro_rules! add_alias {
        ($keycode:tt) => {
            m.insert(paste::paste!{ stringify!([<$keycode:lower>]) }, $keycode);
        };
        ($keycode:tt = $( $alias:expr),*) => {
            add_alias!($keycode);
            $(
                m.insert($alias, $keycode);
            )*
        };
    }

    add_alias!("No");
    add_alias!("A");
    add_alias!("B");
    add_alias!("C");
    add_alias!("D");
    add_alias!("E");
    add_alias!("F");
    add_alias!("G");
    add_alias!("H");
    add_alias!("I");
    add_alias!("J");
    add_alias!("K");
    add_alias!("L");
    add_alias!("M");
    add_alias!("N");
    add_alias!("O");
    add_alias!("P");
    add_alias!("Q");
    add_alias!("R");
    add_alias!("S");
    add_alias!("T");
    add_alias!("U");
    add_alias!("V");
    add_alias!("W");
    add_alias!("X");
    add_alias!("Y");
    add_alias!("Z");
    add_alias!("Kc1" = "1");
    add_alias!("Kc2" = "2");
    add_alias!("Kc3" = "3");
    add_alias!("Kc4" = "4");
    add_alias!("Kc5" = "5");
    add_alias!("Kc6" = "6");
    add_alias!("Kc7" = "7");
    add_alias!("Kc8" = "8");
    add_alias!("Kc9" = "9");
    add_alias!("Kc0" = "0");
    add_alias!("Enter" = "ent", "return");
    add_alias!("Backspace" = "bspc", "bs");
    add_alias!("Tab");
    add_alias!("Space" = "spc", " ");
    add_alias!("Minus" = "mins", "-");
    add_alias!("Equal" = "eql", "=");
    add_alias!("LeftBracket" = "left_bracket", "lbrc", "[");
    add_alias!("RightBracket" = "right_bracket", "rbrc", "]");
    add_alias!("Backslash" = "bsls", "\\");
    add_alias!("NonusHash" = "nonus_hash", "nuhs", "#");
    add_alias!("Semicolon" = "scln", ";");
    add_alias!("Quote" = "quot", "'");
    add_alias!("Grave" = "grv", "`");
    add_alias!("Comma" = "comm", ",");
    add_alias!("Dot" = ".");
    add_alias!("Slash" = "/");
    add_alias!("CapsLock" = "caps_lock", "caps");
    add_alias!("F1");
    add_alias!("F2");
    add_alias!("F3");
    add_alias!("F4");
    add_alias!("F5");
    add_alias!("F6");
    add_alias!("F7");
    add_alias!("F8");
    add_alias!("F9");
    add_alias!("F10");
    add_alias!("F11");
    add_alias!("F12");
    add_alias!("PrintScreen" = "print_screen", "pscr");
    add_alias!("ScrollLock" = "scroll_lock", "scrl");
    add_alias!("Pause" = "paus", "brk", "brmu");
    add_alias!("Insert" = "ins");
    add_alias!("Home");
    add_alias!("End");
    add_alias!("PageUp" = "page_up", "pgup");
    add_alias!("PageDown" = "page_down", "pgdn");
    add_alias!("Delete" = "del");
    add_alias!("Right" = "rght", "->", "→");
    add_alias!("Left" = "<-", "←");
    add_alias!("Down" = "↓");
    add_alias!("Up" = "↑");
    add_alias!("NumLock" = "num_lock", "num");
    add_alias!("KpSlash" = "kp_slash", "psls");
    add_alias!("KpAsterisk" = "kp_asterisk", "past");
    add_alias!("KpMinus" = "kp_minus", "pmns");
    add_alias!("KpPlus" = "kp_plus", "ppls");
    add_alias!("KpEnter" = "kp_enter", "pent");
    add_alias!("KpDecimal" = "kp_decimal", "pdec");
    add_alias!("Kp0" = "kp_0");
    add_alias!("Kp0" = "kp0");
    add_alias!("Kp1" = "kp_1");
    add_alias!("Kp1" = "kp1");
    add_alias!("Kp2" = "kp_2");
    add_alias!("Kp2" = "kp2");
    add_alias!("Kp3" = "kp_3");
    add_alias!("Kp3" = "kp3");
    add_alias!("Kp4" = "kp_4");
    add_alias!("Kp4" = "kp4");
    add_alias!("Kp5" = "kp_5");
    add_alias!("Kp5" = "kp5");
    add_alias!("Kp6" = "kp_6");
    add_alias!("Kp6" = "kp6");
    add_alias!("Kp7" = "kp_7");
    add_alias!("Kp7" = "kp7");
    add_alias!("Kp8" = "kp_8");
    add_alias!("Kp8" = "kp8");
    add_alias!("Kp9" = "kp_9");
    add_alias!("Kp9" = "kp9");
    add_alias!("Kp0" = "kp_0");
    add_alias!("Kp0" = "kp0");
    add_alias!("KpDot" = "kp_dot", "pdot");
    add_alias!("KpEqual" = "kp_equal", "peql");
    add_alias!("NonusBackslash" = "nonus_backslash", "nubs");
    add_alias!("Application" = "app");
    add_alias!("KbPower" = "kb_power");
    add_alias!("F13");
    add_alias!("F14");
    add_alias!("F15");
    add_alias!("F16");
    add_alias!("F17");
    add_alias!("F18");
    add_alias!("F19");
    add_alias!("F20");
    add_alias!("F21");
    add_alias!("F22");
    add_alias!("F23");
    add_alias!("F24");
    add_alias!("Execute" = "exec");
    add_alias!("Help");
    add_alias!("Menu");
    add_alias!("Select" = "slct");
    add_alias!("Stop");
    add_alias!("Again" = "agin");
    add_alias!("Undo");
    add_alias!("Cut");
    add_alias!("Copy");
    add_alias!("Paste" = "pste");
    add_alias!("Find");
    add_alias!("KbMute" = "kb_mute", "mute"); // FIXME: mismatch with QMK. `mute` in QMK is mapped to `KC_AUDIO_MUTE`. The same for the other `Kb*` keys.
    add_alias!("KbVolumeUp" = "kb_volume_up", "volumeup", "volume_up", "volup", "vol_up");
    add_alias!("KbVolumeDown" = "kb_volume_down", "volumedown", "volume_down", "voldown", "vol_down");
    add_alias!("LockingCapsLock" = "lock_caps_lock", "lock_capslock", "lcap");
    add_alias!("LockingNumLock" = "lock_num_lock", "locking_numlock ", "lnum");
    add_alias!("LockingScrollLock" = "lock_scroll_lock", "lock_scrolllock", "lscr");
    add_alias!("KpComma" = "kp_comma", "pcmm");
    add_alias!("KpEqualAs400" = "kp_equal_as400");
    add_alias!("International1" = "international_1", "int1");
    add_alias!("International2" = "international_2", "int2");
    add_alias!("International3" = "international_3", "int3");
    add_alias!("International4" = "international_4", "int4");
    add_alias!("International5" = "international_5", "int5");
    add_alias!("International6" = "international_6", "int6");
    add_alias!("International7" = "international_7", "int7");
    add_alias!("International8" = "international_8", "int8");
    add_alias!("International9" = "international_9", "int9");
    add_alias!("Language1" = "language_1", "lng1");
    add_alias!("Language2" = "language_2", "lng2");
    add_alias!("Language3" = "language_3", "lng3");
    add_alias!("Language4" = "language_4", "lng4");
    add_alias!("Language5" = "language_5", "lng5");
    add_alias!("Language6" = "language_6", "lng6");
    add_alias!("Language7" = "language_7", "lng7");
    add_alias!("Language8" = "language_8", "lng8");
    add_alias!("Language9" = "language_9", "lng9");
    add_alias!("AlternateErase" = "alternate_erase", "eras");
    add_alias!("SystemRequest" = "system_request", "syrq");
    add_alias!("Cancel" = "cncl");
    add_alias!("Clear" = "clr");
    add_alias!("Prior" = "prir");
    add_alias!("Return" = "retn");
    add_alias!("Separator" = "sepr");
    add_alias!("Out");
    add_alias!("Oper");
    add_alias!("ClearAgain" = "clear_again", "clag");
    add_alias!("Crsel" = "crsl");
    add_alias!("Exsel" = "exsl");
    add_alias!("SystemPower" = "system_power", "pwr");
    add_alias!("SystemSleep" = "system_sleep", "slep");
    add_alias!("SystemWake" = "system_wake", "wake");
    add_alias!("AudioMute" = "audio_mute"); // FIXME: mismatch with QMK. See above.
    add_alias!("AudioVolUp" = "audio_vol_up", "audio_volup", "volu");
    add_alias!("AudioVolDown" = "audio_vol_down", "audio_voldown", "vold");
    add_alias!("MediaPlayPause" = "media_play_pause", "mediaplay_pause", "mply");
    add_alias!("MediaSelect" = "media_select", "msel");
    add_alias!("MediaEject" = "media_eject", "ejct");
    add_alias!("Mail");
    add_alias!("Calculator" = "calc");
    add_alias!("MyComputer" = "my_computer", "mycm");
    add_alias!("WwwSearch" = "www_search", "wsch");
    add_alias!("WwwHome" = "www_home", "whom");
    add_alias!("WwwBack" = "www_back", "wbak");
    add_alias!("WwwForward" = "www_forward", "wfwd");
    add_alias!("WwwStop" = "www_stop", "wstp");
    add_alias!("WwwRefresh" = "www_refresh", "wref");
    add_alias!("WwwFavorites" = "www_favorites", "wfav");
    add_alias!("MediaFastForward" = "media_fast_forward", "media_fastforward", "mffd");
    add_alias!("MediaRewind" = "media_rewind", "mrwd");
    add_alias!("BrightnessUp" = "brightness_up", "briu");
    add_alias!("BrightnessDown" = "brightness_down", "brid");
    add_alias!("ControlPanel" = "control_panel", "cpnl");
    add_alias!("Assistant" = "asst");
    add_alias!("MissionControl" = "mission_control", "mctl");
    add_alias!("Launchpad" = "lpad");
    add_alias!("MouseUp" = "mouse_up", "mousecursorup", "mouse_cursor_up", "ms_up");
    add_alias!("MouseDown" = "mouse_down", "mousecursordown", "mouse_cursor_down", "ms_down");
    add_alias!("MouseLeft" = "mouse_left", "mousecursorleft", "mouse_cursor_left", "ms_left");
    add_alias!("MouseRight" = "mouse_right", "mousecursorright", "mouse_cursor_right", "ms_right");
    add_alias!("MouseBtn1" = "mouse_btn_1", "mousebutton1", "mouse_button_1", "ms_btn1");
    add_alias!("MouseBtn2" = "mouse_btn_2", "mousebutton2", "mouse_button_2", "ms_btn2");
    add_alias!("MouseBtn3" = "mouse_btn_3", "mousebutton3", "mouse_button_3", "ms_btn3");
    add_alias!("MouseBtn4" = "mouse_btn_4", "mousebutton4", "mouse_button_4", "ms_btn4");
    add_alias!("MouseBtn5" = "mouse_btn_5", "mousebutton5", "mouse_button_5", "ms_btn5");
    add_alias!("MouseBtn6" = "mouse_btn_6", "mousebutton6", "mouse_button_6", "ms_btn6");
    add_alias!("MouseBtn7" = "mouse_btn_7", "mousebutton7", "mouse_button_7", "ms_btn7");
    add_alias!("MouseBtn8" = "mouse_btn_8", "mousebutton8", "mouse_button_8", "ms_btn8");
    add_alias!("MouseWheelUp" = "mouse_wheelup", "mouse_wheel_up", "ms_whlu");
    add_alias!("MouseWheelDown" = "mouse_wheeldown", "mouse_wheel_down", "ms_whld");
    add_alias!("MouseWheelLeft" = "mouse_wheelleft", "mouse_wheel_left", "ms_whll");
    add_alias!("MouseWheelRight" = "mouse_wheelright", "mouse_wheel_right", "ms_whlr");
    add_alias!("MouseAccel0" = "mouse_accel0", "mouse_accel_0", "mouse_acceleration_0", "ms_acl0");
    add_alias!("MouseAccel1" = "mouse_accel1", "mouse_accel_1", "mouse_acceleration_1", "ms_acl1");
    add_alias!("MouseAccel2" = "mouse_accel2", "mouse_accel_2", "mouse_acceleration_2", "ms_acl2");
    add_alias!("LCtrl" = "lctrl", "leftcontrol", "left_ctrl", "lctl");
    add_alias!("LShift" = "lshift", "leftshift", "left_shift", "lsft");
    add_alias!("LAlt" = "leftalt", "left_alt", "lopt");
    add_alias!("LGui" = "leftgui", "left_gui", "lwin", "lcmd");
    add_alias!("RCtrl" = "rightctrl", "right_control", "rctl");
    add_alias!("RShift" = "rightshift", "right_shift", "rsft");
    add_alias!("RAlt" = "rightalt", "right_alt", "ropt", "algr");
    add_alias!("RGui" = "rightgui", "right_gui", "rwin", "rcmd");

    m
});
