/* CH58x */
MEMORY
{
    /* Code Flash, 448KB max */
  FLASH(rx) : ORIGIN = 0x00000000, LENGTH = 448k
    /* SRAM, 32KB */
    /* up to 0x20007FFF */
  RAM(rwx) : ORIGIN = 0x20000000, LENGTH = 32k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);