// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device capabilities discovered during the connection handshake.
 *
 * The host reads this once after connecting to learn the firmware's layout,
 * feature set, and protocol limits.
 */
export type DeviceCapabilities = { num_layers: number, num_rows: number, num_cols: number, num_encoders: number, max_combos: number, max_combo_keys: number, 
/**
 * Number of macros supported, set by the user at compile time. `0`
 * disables macros: the host MUST NOT use them or consult `macro_space_size`.
 */
max_macros: number, 
/**
 * Byte size of the flat macro region; only meaningful when `max_macros > 0`.
 */
macro_space_size: number, max_morse: number, max_patterns_per_key: number, max_forks: number, storage_enabled: boolean, lighting_enabled: boolean, is_split: boolean, num_split_peripherals: number, ble_enabled: boolean, num_ble_profiles: number, max_payload_size: number, max_bulk_keys: number, macro_chunk_size: number, bulk_transfer_supported: boolean, };
