// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protocol version advertised during the connection handshake.
 */
export type ProtocolVersion = { major: number, minor: number, };
