[package]
name = "rmk-nrf54lm20"
version = "0.1.0"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/rmk-rs/rmk"
repository = "https://github.com/rmk-rs/rmk"
readme = "../../README.md"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk", default-features = false, features = [
    "rynk",
    "async_matrix",
    "nrf54lm20_ble",
    "storage",
    "defmt",
    "watchdog",
] }
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc", rev = "f54b6389ffa2750d4d3a4f5435660cb66b47e51a", default-features = false, features = [
    "defmt",
    "peripheral",
    "central",
    "nrf54lm20-app-s",
] }
# nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc", rev = "f54b6389ffa2750d4d3a4f5435660cb66b47e51a", default-features = false, features = [
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc", rev = "f54b6389ffa2750d4d3a4f5435660cb66b47e51a", default-features = false, features = [
    "defmt",
    "critical-section-impl",
    "nrf54lm20-app-s",
] }
bt-hci = { version = "0.9", features = ["defmt"] }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.11", features = [
    "defmt",
    "nrf54lm20-app-s",
    "time-driver-grtc",
    "gpiote",
    "unstable-pac",
    "time",
] }
embassy-executor = { version = "0.10", features = [
    "defmt",
    "platform-cortex-m",
    "executor-thread",
] }
defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }
static_cell = "2"


[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[[bin]]
name = "rmk-nrf54lm20"
test = false
bench = false

[profile.dev]
codegen-units = 1
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = "unwind"

[profile.release]
codegen-units = 1
debug = true
opt-level = "z"
overflow-checks = false
lto = "fat"

[patch.crates-io]
embassy-nrf = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-hal-internal = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "e6626ce6c04fb5408449a2d209b6809afd965b4f" }
