/* rmk-memory.x for for RP2040 2 MB — generated by rmk-boot
 *
 * Provides both the MEMORY layout (absolute XIP addresses) and
 * flash-relative DFU symbols consumed by init_flash_from_linkerscript().
 *
 * If your board has a different flash size, replace this file with the
 * matching file from the rmk-boot releases:
 *   https://github.com/rmk-rs/rmk-boot/releases
 */

MEMORY {
  FLASH : ORIGIN = 0x10007000, LENGTH = 1015808   /* ACTIVE region */
  RAM   : ORIGIN = 0x20000000, LENGTH = 256K                       /* SRAM */
}

/* DFU partition symbols — offsets relative to flash start */
__rmk_boot_state_offset   = 0x6000;
__rmk_boot_state_size     = 0x1000;
__rmk_boot_dfu_offset     = 0xFF000;
__rmk_boot_dfu_size       = 0xF9000;
__rmk_boot_storage_offset = 0x1F8000;
__rmk_boot_storage_size   = 0x8000;
