# Clean the individual Cargo target directories generated by the CI scripts.
clean_cargo_target() {
    target_dir="$1"
    manifest="$2"
    if [ -d "$target_dir" ]; then
        echo "Cleaning $target_dir"
        cargo clean --manifest-path "$manifest" --target-dir "$target_dir"
    fi
}

clean_cargo_target ./target/ci/check-stable rmk/Cargo.toml
clean_cargo_target ./target/ci/check-nightly rmk/Cargo.toml
clean_cargo_target ./target/ci/clippy-stable rmk/Cargo.toml
clean_cargo_target ./target/ci/test rmk/Cargo.toml
clean_cargo_target ./target/ci/host rynk/Cargo.toml
rmdir ./target/ci ./target 2>/dev/null || true

# Clean build caches
for dir in examples/use_rust/*/ examples/use_config/*/; do
    if [ -d "$dir" ] && [ -d "$dir/src" ]; then
        cd "$dir"
        echo "Cleaning $dir"
        cargo clean
        cd ../../..
    fi
done

for dir in rmk/ rmk-config/ rmk-macro/ rmk-types/ rynk/; do
    if [ -d "$dir" ] && [ -d "$dir/src" ]; then
        cd "$dir"
        echo "Cleaning $dir"
        cargo clean
        cd ..
    fi
done
