# Clean the individual Cargo target directories generated by the CI scripts.
for target_dir in ./target/ci/*/; do
    if [ -d "$target_dir" ]; then
        echo "Cleaning $target_dir"
        cargo clean --manifest-path rmk/Cargo.toml --target-dir "$target_dir"
    fi
done
rmdir ./target/ci ./target 2>/dev/null || true

# Clean build caches
for dir in examples/use_rust/*/ examples/use_config/*/; do
    if [ -d "$dir" ] && [ -d "$dir/src" ]; then
        cd "$dir"
        echo "Cleaning $dir"
        cargo clean
        cd ../../..
    fi
done

for dir in rmk/ rmk-config/ rmk-macro/ rmk-types/ rynk/; do
    if [ -d "$dir" ] && [ -d "$dir/src" ]; then
        cd "$dir"
        echo "Cleaning $dir"
        cargo clean
        cd ..
    fi
done
