cd rmk && cargo fmt && cd ..
cd rmk-config && cargo fmt && cd ..
cd rmk-macro && cargo fmt && cd ..
cd examples/use_rust/esp32c3_ble && cargo fmt && cd ../../..
cd examples/use_rust/esp32c6_ble && cargo fmt && cd ../../..
cd examples/use_rust/esp32s3_ble && cargo fmt && cd ../../..
cd examples/use_rust/hpm5300 && cargo fmt && cd ../../.. 
cd examples/use_rust/nrf52832_ble && cargo fmt && cd ../../..
cd examples/use_rust/nrf52840 && cargo fmt && cd ../../..
cd examples/use_rust/nrf52840_ble && cargo fmt && cd ../../..
cd examples/use_rust/nrf52840_ble_split && cargo fmt && cd ../../..
cd examples/use_rust/rp2040 && cargo fmt && cd ../../..
cd examples/use_rust/rp2040_split && cargo fmt && cd ../../..
cd examples/use_rust/stm32f1 && cargo fmt && cd ../../..
cd examples/use_rust/stm32f4 && cargo fmt && cd ../../..
cd examples/use_rust/stm32h7 && cargo fmt && cd ../../..  
cd examples/use_rust/stm32h7_async && cargo fmt && cd ../../.. 
cd examples/use_config/esp32c3_ble && cargo fmt && cd ../../..
cd examples/use_config/esp32c6_ble && cargo fmt && cd ../../..
cd examples/use_config/esp32s3_ble && cargo fmt && cd ../../..
cd examples/use_config/nrf52832_ble && cargo fmt && cd ../../.. 
cd examples/use_config/nrf52840_ble && cargo fmt && cd ../../.. 
cd examples/use_config/nrf52840_ble_split && cargo fmt && cd ../../.. 
cd examples/use_config/nrf52840_usb && cargo fmt && cd ../../.. 
cd examples/use_config/rp2040 && cargo fmt && cd ../../.. 
cd examples/use_config/rp2040_split && cargo fmt && cd ../../.. 
cd examples/use_config/stm32f1 && cargo fmt && cd ../../..
cd examples/use_config/stm32f4 && cargo fmt && cd ../../..
cd examples/use_config/stm32h7 && cargo fmt && cd ../../..