cd rmk && cargo +nightly fmt && cd ..
cd rmk-macro && cargo +nightly fmt && cd ..
cd examples/use_rust/esp32c3_ble && cargo +esp fmt && cd ../../..
cd examples/use_rust/esp32c6_ble && cargo +esp fmt && cd ../../..
cd examples/use_rust/esp32s3_ble && cargo +esp fmt && cd ../../..
cd examples/use_rust/hpm5300 && cargo +nightly fmt && cd ../../.. 
cd examples/use_rust/nrf52832_ble && cargo +nightly fmt && cd ../../..
cd examples/use_rust/nrf52840 && cargo +nightly fmt && cd ../../..
cd examples/use_rust/nrf52840_ble && cargo +nightly fmt && cd ../../..
cd examples/use_rust/nrf52840_ble_split && cargo +nightly fmt && cd ../../..
cd examples/use_rust/rp2040 && cargo +nightly fmt && cd ../../..
cd examples/use_rust/rp2040_direct_pin && cargo +nightly fmt && cd ../../..
cd examples/use_rust/rp2040_split && cargo +nightly fmt && cd ../../..
cd examples/use_rust/stm32f1 && cargo +nightly fmt && cd ../../..
cd examples/use_rust/stm32f4 && cargo +nightly fmt && cd ../../..
cd examples/use_rust/stm32h7 && cargo +nightly fmt && cd ../../..  
cd examples/use_rust/py32f07x && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/esp32c3_ble && cargo +esp fmt && cd ../../..
cd examples/use_config/esp32c6_ble && cargo +esp fmt && cd ../../..
cd examples/use_config/esp32s3_ble && cargo +esp fmt && cd ../../..
cd examples/use_config/nrf52832_ble && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/nrf52840_ble && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/nrf52840_ble_split && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/rp2040 && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/rp2040_direct_pin && cargo +nightly fmt && cd ../../..
cd examples/use_config/rp2040_split && cargo +nightly fmt && cd ../../.. 
cd examples/use_config/stm32f1 && cargo +nightly fmt && cd ../../..
cd examples/use_config/stm32f4 && cargo +nightly fmt && cd ../../..
cd examples/use_config/stm32h7 && cargo +nightly fmt && cd ../../..