[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'sftool -c SF32LB52 --port <YOUR_PORT_HERE> write_flash ftab.bin@0x12000000'

# Currently, probe-rs can only execute `attach`, not `run` or `download`.
# Refer to https://github.com/OpenSiFli/sifli-rs/blob/main/docs/flash_and_debug.md
# runner = "probe-rs attach --chip SF32LB52" 

# Cortex-M33 has MSPLIM, so we don't need flip-link

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
KEYBOARD_TOML_PATH =  { value = "keyboard.toml", relative = true }
SIFLI_UART_DEBUG = "1"
