[package]
name = "rmk-pi-pico-w"
version = "0.2.0"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
readme = "../../README.md"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { path = "../../../rmk", features = ["pico_w_ble", "rp2040", "split"] }
embassy-time = { version = "0.5", features = ["defmt"] }
embassy-rp = { version = "0.8", features = [
    "rp2040",
    "defmt",
    "time-driver",
    "critical-section-impl",
] }
embassy-executor = { version = "0.9", features = [
    "defmt",
    "arch-cortex-m",
    "executor-thread",
] }
cortex-m-rt = "0.7.5"
portable-atomic = { version = "1.11", features = ["critical-section"] }
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
cyw43 = { version = "0.5.0", features = ["defmt", "firmware-logs", "bluetooth"] }
cyw43-pio = { version = "0.8.0", features = ["defmt"] }
static_cell = "2"
bt-hci = { version = "0.5", default-features = false, features = ["defmt"] }
rand = { version = "0.8.4", default-features = false }
rand_core = { version = "0.6" }
rand_chacha = { version = "0.3", default-features = false }


[features]
skip-cyw43-firmware = []
# avoid having to use --allow-multiple-definition linker flag
# on macOS with Apple Silicon at least
# default = ["rp-pico/disable-intrinsics"]

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"
reqwest = { version = "0.12.9", features = ["blocking"]}

# Split keyboard example
[[bin]]
name = "central"
path = "src/central.rs"

[[bin]]
name = "peripheral"
path = "src/peripheral.rs"

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"

[patch.crates-io]
cyw43 = { git = "https://github.com/embassy-rs/embassy", rev = "8394e13" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "8394e13" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "8394e13" }