[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "rp2040"

[matrix]
# Row and col pins are mandatory
row_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9"]
col_pins = ["PIN_19", "PIN_20", "PIN_21"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        [
            "A",
            "B",
            "C",
        ],
        [
            "Kc1",
            "Kc2",
            "Kc3",
        ],
        [
            "LCtrl",
            "MO(1)",
            "LShift",
        ],
        [
            "OSL(1)",
            "LT(2, Kc9)",
            "LM(1, LShift | LGui)",
        ],
    ],
    [
        [
            "_",
            "TT(1)",
            "TG(2)",
        ],
        [
            "_",
            "_",
            "_",
        ],
        [
            "_",
            "_",
            "_",
        ],
        [
            "_",
            "_",
            "_",
        ],
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[rmk]
morse_max_num = 8
max_patterns_per_key = 8
